[project]
name = 'lottery-staking'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.bridge]
path = 'contracts/bridge.clar'
clarity_version = 3
epoch = 3.1

[contracts.lottery]
path = 'contracts/lottery.clar'
clarity_version = 2
epoch = 2.5

[contracts.prediction-market]
path = 'contracts/prediction-market.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
